site:
  title: "Red Hat Enterprise Linux: Create System Images Using Image Builder"
  start_page: imagebuilder::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
