= Image builder features and benefits 

== What is image builder?

Image builder is an image-building tool and live bootable image creator. You can use image builder to create custom deployable images, including selected packages, running a post-install configuration, and more. You can also include third-party packages and updated RHEL Errata content. You can produce images in various formats for deployment to multiple environments.

Comprehensive documentation on image builder is available alongside other product documentation at https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/composing_a_customized_rhel_system_image/index[Composing a customized RHEL system image^]

 Note: Image builder was called composer through the RHEL 8 Beta, and the name changed just before the Genral Availability (GA) release of RHEL 8.0. You still see composer in package names and service names.
 
== Need for image builder

Before image builder, creating customized RHEL images meant getting media from the Red Hat customer portal and manually applying changes. Red Hat did not support those customized images, only the ISO and virtual machine images provided directly from the customer portal.

The demand for a new approach came from multiple places. Clients and partners often made feature requests to Red Hat seeking a supported ability to customize RHEL images for their specific needs. This feature was essential for Red Hat's strategy to become the leading cloud solution in the market.

== Features and benefits

Image builder provides the following features and benefits:

- Provides an end user with the ability to create supported custom RHEL images according to their needs.
- Reduces deployment and configuration time on public cloud services.
- Supports various output image formats for various environments.
- Enables customers to create images for disconnected environments.
- Permits users to configure output images for custom repositories (diverging from the defaults).
- Provides package selection and configuration from a user-friendly web user interface (UI) in the RHEL 9 web console.
- Allows users to save and alter image configuration so they can create multiple replicas with a few UI selections.
- Image builder supports creating bootable installer images to install a bare metal system.